prober_name_or_path: /data1/linjk/work/prorec/save/allcg_src_prober_codellama-13b-last1unfreeze
prober_subfolder: checkpoint-1500
dualencoder_name_or_path: /data1/linjk/work/prorec/save/CASP/cg-casp-moco-lmpa-c-only
dualencoder_subfolder: checkpoint-19500
src_model_name_or_path: /data3/linjk/model/CodeLlama-13b-hf
asm_tokenizer_name_or_path: /data1/linjk/work/prorec/model/PurCL/longcodeart-ep0.3-block200-26m/checkpoint-25000
dataset_name: 
output_dir: ../save
output_file: max_new_25_rseq_50_results-p0.75-k500-4bit-last1unfreeze.json
quantization: 4bit

max_new_tokens: 25
num_return_sequences: 10
temperature: 1.0
top_k: 500
top_p: 0.75


parallel_inference_split: 1/1

per_device_eval_batch_size: 2

remove_unused_columns: false

cache_dir: /data1/linjk/work/prorec/save/.cache
